---
language: java

sudo: required

#install apt packages
addons:
  apt:
    packages:
      - python-pip

# install some more stuff
install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - mvn clean install -e -Dmaven.javadoc.skip=true

branches:
  only:
  - master

notifications:
  email:
  - ci.notifications@digitalsandpit.io