---
language: java

sudo: required

#install apt packages

addons:
  apt:
    packages:
      - python-pip

# install some more stuff
install:
  # Install ansible
  - sudo pip install ansible

  # Adding an /etc/ansible/hosts
  - sudo mkdir /etc/ansible
  - sudo touch /etc/ansible/hosts
  - sudo printf '[local]\nlocalhost\n\n[webserver]'>/etc/ansible/hosts

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - mvn clean install -e -Dmaven.javadoc.skip=true

branches:
  only:
  - master

notifications:
  email:
  - ci.notifications@digitalsandpit.io