package io.digitalsandpit.garden.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import io.digitalsandpit.garden.model.LipoSocEvent;

import java.util.Date;

@DynamoDBTable(tableName = "lipo-soc-table")
public class LipoSoc {

    private String id;
    private Date timestamp;
    private String coreid;
    private String name;
    private double data;

    public LipoSoc(LipoSocEvent event) {
        this.timestamp = event.getTimestamp();
        this.coreid = event.getCoreid();
        this.name = event.getName();
        this.data = event.getData();
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public double getData() {
        return data;
    }

    @DynamoDBAttribute
    public Date getTimestamp() {
        return timestamp;
    }

    @DynamoDBAttribute
    public String getCoreid() {
        return coreid;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setData(double data) {
        this.data = data;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public void setCoreid(String coreid) {
        this.coreid = coreid;
    }

    public void setName(String name) {
        this.name = name;
    }


}
