---
# file: roles/provision-ec2/tasks/main.yml

  - name: Create a security group
    ec2_group:
      name: "{{ security_group }}"
      description: "Default group for all applications"
      region: "{{ region }}"
      rules:
        - proto: tcp
          #type: ssh
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          #type: all
          cidr_ip: 0.0.0.0/0

  - name: Launch a new EC2 instance
    ec2:
      group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      instance_profile_name: "{{ iam_role }}"
      image: "{{ image }}"
      wait: true
      region: "{{ region }}"
      keypair: "{{ keypair }}"
      count: "{{ count }}"
    register: ec2

  # This Elastic IP shouldn't really be hard-coded. But it is tied to garden.digitalsandpit.io
  # Once fixed it will impact the three following tasks
  - name: Associate the instance with pre-defined elastic IP
    ec2_eip:
      device_id: "{{ item.id }}"
      region: "{{ item.region }}"
      ip: "{{ elastic_ip }}"
    with_items: "{{ ec2.instances }}"

  - name: Add the EC2 instances to the local /.hosts file
    lineinfile:
      dest: "inventory/hosts"
      insertafter: "[webservers]"
      line: "{{ elastic_ip }}"
    with_items: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ elastic_ip }}"
      port: 22
      state: started
    with_items: "{{ ec2.instances }}"

  - name: Add tag to instances
    ec2_tag:
      resource: "{{ item.id }}"
      region: "{{ region }}"
      state: present
    with_items: "{{ ec2.instances }}"
    args:
      tags:
        Name: PhotonService