---
# file: roles/photon-service/tasks/main.yml

  - name: Install the java 8 jre
    yum:
      name: java-1.8.0-openjdk
      state: present
    become: true

  - name: Copy PhotonService.service to systemd home
    copy:
      src: ../photon-service/src/main/scripts/PhotonService.service
      dest: /usr/lib/systemd/system
      mode: 0544
    become: true

  - name: Copy runPhotonService.sh to ec2-user home
    copy:
      src: ../photon-service/src/main/scripts/runPhotonService.sh
      dest: /home/ec2-user/runPhotonService.sh
      mode: 0544

  - name: Copy jar file to ec2-user home
    copy:
      src: ../photon-service/target/photon-service-1.0-SNAPSHOT.jar
      dest: /home/ec2-user/photon-service-.jar

  - name: Unlink current app version
    file:
      path: /home/ec2-user/photon-service.jar
      state: absent

  - name: Link new app version
    file:
      path: /home/ec2-user/photon-service.jar
      src: /home/ec2-user/photon-service-.jar
      state: link

  - name: Stop app from running
    service:
      name: PhotonService
      state: stopped
    become: true

  - name: Start app up again
    service:
      name: PhotonService
      state: started
    become: true
