---
# file: roles/provision-dynamodb/tasks/main.yml

  - name: Create dynamo table with hash and range primary key
    dynamodb_table:
      name: lipo-soc-table
      region: "{{ region }}"
      hash_key_name: id
      hash_key_type: STRING
      range_key_name: timestamp
      range_key_type: STRING
      read_capacity: 2
      write_capacity: 2
