---
#file: roles/provision-dynamodb/defaults/main.yml
#  instance_type: t2.micro
#  security_group: AppServerGroup  # Change based on your default app server security group
#  image: ami-02ace471             # Red Hat Enterprise Linux 7.3 (HVM), SSD Volume Type
#  region: eu-west-1               # Ireland
#  keypair: ansible                # Change based on the keypair you're using
#  count: 1                        # Only want one EC2 instance
#  elastic_ip: 52.213.130.123      # This shouldn't really be hard-coded but is currently associated with garden.digitalsandpit.io via route53