---
# file site.yml
  - hosts: localhost
    connection: local
    gather_facts: False
    roles:
      - provision-ec2
      - provision-dynamodb

  - hosts: webservers
    user: ec2-user
    roles:
      - photon-service